language: php
php: 7.0
sudo: false

env:
  global:
    - SIMPLETEST_DB=mysql://root:@127.0.0.1/bargain
    - SIMPLETEST_BASE_URL="http://localhost:8888"
  matrix:
    - MODE=cs
    - MODE=kernal
    - MODE=functional

mysql:
  database: bargain
  username: root

before_install:
  - echo 'sendmail_path = /bin/true' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - phpenv config-rm xdebug.ini
  - composer --verbose self-update --$COMPOSER_CHANNEL
  - composer --version

install:
  - composer --verbose install

script:
  - if [[ $MODE == cs ]]; then
    ./vendor/bin/phpcs web/modules/custom;
    fi
  - if [[ $MODE == kernal ]]; then
    bash scripts/travis/kernal.sh;
    fi
  - if [[ $MODE == functional ]]; then
    bash scripts/travis/functional.sh;
    fi
