language: php
php:
  - 5.6
  - 7.0

sudo: false

env:
  global:
    - SIMPLETEST_DB=sqlite://tmp/site.sqlite
    - SIMPLETEST_BASE_URL="http://127.0.0.1:8080"
  matrix:
    - MODE=cs
    - MODE=kernal

before_install:
  - echo 'sendmail_path = /bin/true' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - phpenv config-rm xdebug.ini
  - composer --verbose self-update --$COMPOSER_CHANNEL
  - composer --version

install:
  - composer --verbose install


script:
  - cd $TRAVIS_BUILD_DIR/web
  - sleep 3
  - if [[ $MODE == cs ]]; then
    echo "CS";
    fi
  - if [[ $MODE == kernal ]]; then
    ./../vendor/bin/drush site-install --verbose --yes --db-url=sqlite://tmp/site.sqlite;
    ./../vendor/bin/drush runserver http://127.0.0.1:8080 &
    echo "kernal";
    fi
#  # Skip core/tests/Drupal/Tests/ComposerIntegrationTest.php because web/ has no composer.json
#  # Ignore PageCache group temporarily, @see https://www.drupal.org/node/2770673
#  - ./../vendor/bin/phpunit -c core --testsuite unit --exclude-group Composer,DependencyInjection,PageCache
#  - ./../vendor/bin/drush
#  - ./../vendor/bin/drupal
