language: php
php:
  - 5.6
  - 7.0

sudo: false

env:
  matrix:
    - MODE=cs
    - MODE=kernal

mysql:
  database: bargain
  username: root

before_install:
  - echo 'sendmail_path = /bin/true' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - phpenv config-rm xdebug.ini
  - composer --verbose self-update --$COMPOSER_CHANNEL
  - composer --version

install:
  - composer --verbose install

script:
  - export SIMPLETEST_DB=mysql://root:@127.0.0.1/bargain
  - export SIMPLETEST_BASE_URL="http://127.0.0.1:8080"
  - if [[ $MODE == cs ]]; then
    ./vendor/bin/phpcs web/modules/custom;
    fi
  - if [[ $MODE == kernal ]]; then
    bash scripts/travis/unit.sh;
    fi
